import { mkdtemp, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, expect, it } from "vitest";
import { buildWorkshopVideoHtml, executeOne } from "./executor.js";
import { applyWorkshopAction, cancelVideoRender, readWorkshopState } from "./workshop-service.js";
describe("storyboard render composition", () => { it("writes the approved current storyboard into the HyperFrames composition", () => { const root = join(tmpdir(), `workshop-composition-${Date.now()}`); applyWorkshopAction("approveBrief", root); applyWorkshopAction("lockManualStyle", root); applyWorkshopAction("approveStoryboard", root); const state = readWorkshopState(root); const html = buildWorkshopVideoHtml(state); expect(html).toContain(state.storyboard.panels[0]!.title); expect(html).toContain(state.storyboard.panels[1]!.narration); expect(html).toContain("deterministic local placeholder tone"); }); });
describe("worker executor", () => { it("requeues one failed render with retained error, then blocks after the retry budget", async () => { const root = await mkdtemp(join(tmpdir(), "workshop-executor-")); applyWorkshopAction("approveBrief", root); applyWorkshopAction("lockManualStyle", root); applyWorkshopAction("approveStoryboard", root); applyWorkshopAction("renderVideo", root); const first = await executeOne(root, async () => { throw new Error("renderer unavailable"); }); expect(first.state).toBe("failed"); expect(readWorkshopState(root).videoState).toBe("queued"); const second = await executeOne(root, async () => { throw new Error("renderer unavailable"); }); expect(second.state).toBe("failed"); expect(readWorkshopState(root).videoState).toBe("blocked"); await rm(root, { recursive: true, force: true }); }); });
describe("worker cancellation", () => { it("cancels a queued video job and blocks the render state", async () => { const root = await mkdtemp(join(tmpdir(), "workshop-cancel-")); applyWorkshopAction("approveBrief", root); applyWorkshopAction("lockManualStyle", root); applyWorkshopAction("approveStoryboard", root); applyWorkshopAction("renderVideo", root); expect(cancelVideoRender(root).videoState).toBe("blocked"); await expect(executeOne(root)).resolves.toMatchObject({ state: "idle" }); await rm(root, { recursive: true, force: true }); }); });
