"use client";

import React, { useEffect, useMemo, useState, type ReactNode } from "react";
import dynamic from "next/dynamic";

type ObjectView = "map" | "brief" | "outputs" | "storyboard";
type Sheet = "sources" | "library" | "details" | "capture" | "add-source" | null;
type SourceItem = { id: string; type: "TXT" | "PDF" | "WEB"; title: string; origin: string; claimCount: number; excerpt: string; locator: string; permission: "private" | "sanitized" | "shareable" };
type MapNode = { id: string; title: string; body: string; kind: "grounded" | "derived" | "creative"; locator: string; sourceId?: string; x: number; y: number };
type ManualStylePayload = { name: string; accent: string; ink: string; paper: string; logos: string[]; licensedFonts: string[]; references: string[]; negativeRules: string[]; intentProfile: "client_facing_pitch" | "board_deck" | "internal_workshop" };
type PersistedWorkshop = { title: string; briefApproved: boolean; storyboardApproved: boolean; videoState: "blocked" | "queued" | "rendering" | "rendered"; sourceItems: SourceItem[]; activeSourceIds: string[]; sourceChunks?: { id: string; sourceId: string; text: string; locator: string }[]; claims?: { id: string; sourceId: string; chunkId: string; text: string; locator: string }[]; candidates?: { id: string; category: string; text: string; locator: string }[]; mapNodes: MapNode[]; mapEdges?: { id: string; from: string; to: string; kind: string; label?: string }[]; frame?: { version: number; markdown: string; stale: boolean }; style?: { version: number; name: string; accent: string; ink: string; paper: string; stale: boolean }; assetPlan?: { version: number; stale: boolean; evidenceClaimIds: string[] }; storyboard: { version: number; stale: boolean; panels: { id: string; title: string; narration: string; durationSeconds: number; approved: boolean; stale: boolean }[] }; imageBatch?: { id: string; stale: boolean; panels: { id: string; version: number; prompt: string; state: "planned" | "selected_for_regeneration" | "failed" }[] }; outputs: { id: string; type: "deck" | "infographic"; stale: boolean; artifactPath: string; claimIds?: string[] }[] };
const ExcalidrawMap = dynamic<{ nodes: MapNode[]; editable: boolean; onSync: (nodes: Pick<MapNode, "id" | "title" | "x" | "y">[]) => void }>(() => import("./excalidraw-map.js").then((module) => module.ExcalidrawMap), { ssr: false });

export default function WorkshopPage() {
  const [state, setState] = useState<PersistedWorkshop | null>(null); const [view, setView] = useState<ObjectView>("map"); const [sheet, setSheet] = useState<Sheet>(null);
  const [selectedNodeId, setSelectedNodeId] = useState(""); const [selectedSource, setSelectedSource] = useState<SourceItem | null>(null); const [selectedPanelId, setSelectedPanelId] = useState(""); const [mapEditing, setMapEditing] = useState(false); const [notice, setNotice] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  useEffect(() => { void reload(); }, []);
  const selectedNode = useMemo(() => state?.mapNodes.find((node) => node.id === selectedNodeId), [state, selectedNodeId]);
  const selectedPanel = useMemo(() => state?.storyboard.panels.find((panel) => panel.id === selectedPanelId) ?? state?.storyboard.panels[0], [state, selectedPanelId]);
  const canDeliver = Boolean(state?.briefApproved && state.style && !state.style.stale);
  const currentTitle: Record<ObjectView, string> = { map: "Map", brief: "Brief", outputs: "Outputs", storyboard: "Storyboard" };
  async function reload() { const response = await fetch("/api/workshop"); if (response.ok) setState(await response.json() as PersistedWorkshop); }
  async function post(body: Record<string, unknown>) { setBusy(true); setNotice(null); try { const response = await fetch("/api/workshop", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) }); const next = await response.json() as PersistedWorkshop & { error?: string }; if (!response.ok) throw new Error(next.error ?? "Workshop action failed"); setState(next); return next; } catch (error) { setNotice(error instanceof Error ? error.message : "Workshop action failed"); return null; } finally { setBusy(false); } }
  function open(next: ObjectView) { setView(next); setSheet(null); setMapEditing(false); }
  function cite(sourceId?: string) { const source = state?.sourceItems.find((item) => item.id === sourceId) ?? state?.sourceItems[0] ?? null; setSelectedSource(source); setSheet("sources"); }
  async function createOutput(outputType: "deck" | "infographic") { const next = await post({ action: "generateOutput", outputType }); if (next) { setNotice(`${outputType === "deck" ? "Presentation" : "Infographic"} created from the current brief, style, and active sources.`); open("outputs"); } }
  return <main className="workshop-shell">
    <header className="workshop-header"><div className="header-title"><button className="back-button" aria-label="Back to Map" disabled={view === "map"} onClick={() => open("map")}>‹</button><button className="object-title" onClick={() => setSheet("library")}>WorkshopLM <span>/</span> {currentTitle[view]} <i>⌄</i></button><div className="phase-spine" aria-label="Workshop flow"><span className="active">Capture</span><i>→</i><span className={state?.briefApproved ? "active" : ""}>Shape</span><i>→</i><span className={canDeliver ? "active" : ""}>Deliver</span></div></div><div className="header-actions"><button className="text-button host-return" onClick={() => window.parent.focus()}>Continue in ChatGPT</button><button className="text-button source-trigger" onClick={() => setSheet("sources")}>Sources <strong>{state?.activeSourceIds.length ?? 0} of {state?.sourceItems.length ?? 0}</strong></button><button className="text-button library-trigger" onClick={() => setSheet("library")}>Outputs</button><button className="icon-only" aria-label="Workshop details" onClick={() => setSheet("details")}>•••</button>{view === "map" && <button className="primary-button" disabled={busy || !state?.mapNodes.length || Boolean(state?.briefApproved && !state.frame?.stale)} onClick={() => { void post({ action: "approveBrief" }).then((next) => next && open("brief")); }}>{state?.briefApproved && !state.frame?.stale ? "Brief approved" : "Approve brief"}</button>}{view === "storyboard" && <button className="primary-button" disabled={busy || Boolean(state?.storyboardApproved) || Boolean(state?.storyboard.stale)} onClick={() => { void post({ action: "approveStoryboard" }); }}>{state?.storyboardApproved ? "Storyboard approved" : "Approve storyboard"}</button>}</div></header>
    {notice && <div className="notice" role="status"><span>{notice}</span><button onClick={() => setNotice(null)} aria-label="Dismiss">×</button></div>}
    <section className="object-canvas" aria-label={currentTitle[view]}>{view === "map" && <MapCanvas state={state} selectedNode={selectedNode} mapEditing={mapEditing} onMapEditing={() => setMapEditing((value) => !value)} onSelect={setSelectedNodeId} onSync={(canvasNodes) => { void post({ action: "syncMapCanvas", canvasNodes }); }} onCite={cite} />}{view === "brief" && <BriefView state={state} busy={busy} onPost={post} onCite={cite} />}{view === "outputs" && <OutputsView state={state} busy={busy} onCreateOutput={createOutput} onImages={() => { void post({ action: "createImageBatch" }); }} onStoryboard={() => { void post({ action: "generateAssetPlan" }).then((next) => next && post({ action: "generateStoryboard" }).then((made) => made && open("storyboard"))); }} onCite={cite} />}{view === "storyboard" && <StoryboardView storyboard={state?.storyboard} approved={Boolean(state?.storyboardApproved)} panel={selectedPanel} busy={busy} videoState={state?.videoState} onSelect={setSelectedPanelId} onPost={post} onCite={cite} />}</section>
    {sheet === "sources" && <SourcesSheet sources={state?.sourceItems ?? []} activeIds={state?.activeSourceIds ?? []} selected={selectedSource} onClose={() => setSheet(null)} onSelect={setSelectedSource} onToggle={(sourceId) => { const current = state?.activeSourceIds ?? []; const next = current.includes(sourceId) ? current.filter((id) => id !== sourceId) : [...current, sourceId]; void post({ action: "setActiveSourceScope", sourceIds: next }); }} onAdd={() => setSheet("add-source")} onCapture={() => setSheet("capture")} onShowMap={(source) => { setSelectedNodeId(state?.mapNodes.find((node) => node.sourceId === source.id)?.id ?? ""); open("map"); }} />}
    {sheet === "library" && <LibrarySheet state={state} canDeliver={canDeliver} onClose={() => setSheet(null)} onOpen={open} />}{sheet === "details" && <DetailsSheet state={state} node={selectedNode} onClose={() => setSheet(null)} onExtract={() => { void post({ action: "extractCandidates" }); }} />}{sheet === "add-source" && <AddSourceSheet onClose={() => setSheet("sources")} onPost={post} />}{sheet === "capture" && <CaptureSheet onClose={() => setSheet("sources")} onPost={post} />}
  </main>;
}

function MapCanvas({ state, selectedNode, mapEditing, onMapEditing, onSelect, onSync, onCite }: { state: PersistedWorkshop | null; selectedNode?: MapNode; mapEditing: boolean; onMapEditing: () => void; onSelect: (id: string) => void; onSync: (nodes: Pick<MapNode, "id" | "title" | "x" | "y">[]) => void; onCite: (sourceId?: string) => void }) { const nodes = state?.mapNodes ?? []; const displayNodes = nodes.filter((node) => !node.sourceId || state?.activeSourceIds.includes(node.sourceId)); return <div className={`map-canvas ${mapEditing ? "map-editing" : ""}`}><div className="map-caption"><span>Shape · evidence becoming an editable Map</span><button onClick={onMapEditing}>{mapEditing ? "Done editing" : "Edit Map"}</button></div>{mapEditing && <ExcalidrawMap nodes={displayNodes} editable onSync={onSync} />}{!mapEditing && <>{displayNodes.map((node) => <button key={node.id} className={`map-note ${node.kind} ${selectedNode?.id === node.id ? "selected-note" : ""}`} style={{ left: `clamp(116px, ${node.x}%, calc(100% - 116px))`, top: `${node.y}%` }} onClick={() => onSelect(node.id)}><span>{node.kind}</span><strong>{node.title}</strong><p>{node.body}</p><small>{node.locator}</small></button>)}</>}{selectedNode && !mapEditing && <aside className="map-context"><span className={`evidence-dot ${selectedNode.kind}`} /><div><strong>{selectedNode.title}</strong><p>{selectedNode.locator}</p></div><button className="citation-chip" onClick={() => onCite(selectedNode.sourceId)}>Source</button></aside>}</div>; }

function BriefView({ state, busy, onPost, onCite }: { state: PersistedWorkshop | null; busy: boolean; onPost: (body: Record<string, unknown>) => Promise<PersistedWorkshop | null>; onCite: (sourceId?: string) => void }) { const [name, setName] = useState(state?.style?.name ?? "WorkshopLM editorial"); const [accent, setAccent] = useState(state?.style?.accent ?? "#1668E3"); const lock = () => { const style: ManualStylePayload = { name, accent, ink: "#0D0D0D", paper: "#FFFFFF", logos: [], licensedFonts: ["system-ui"], references: ["calm editorial work surface"], negativeRules: ["no decorative gradients"], intentProfile: "client_facing_pitch" }; void onPost({ action: "lockManualStyle", manualStyle: style }); }; return <article className="document-view"><div className="document-main"><p className="eyebrow">Shape · approved production brief</p><h1>Brief</h1><p className="document-intro">{state?.frame && !state.frame.stale ? "This is the approved contract for finished work." : "Approve the current Map to materialize a source-grounded brief."}</p><pre>{state?.frame?.markdown ?? "No approved brief yet."}</pre>{state?.claims?.slice(0, 3).map((claim) => <button className="citation-chip document-citation" key={claim.id} onClick={() => onCite(claim.sourceId)}>{claim.locator}</button>)}</div><aside><span className={state?.frame && !state.frame.stale ? "state current" : "state waiting"}>{state?.frame && !state.frame.stale ? `Current · Map v${state.frame.version}` : "Waiting for Map approval"}</span>{state?.frame && !state.frame.stale && <section className="style-settings"><h2>Style</h2><p>Set the visual contract once. New deliverables inherit it.</p><label>Foundation name<input value={name} onChange={(event) => setName(event.target.value)} /></label><label>Accent<input value={accent} onChange={(event) => setAccent(event.target.value)} /></label><button className="primary-button" disabled={busy} onClick={lock}>{state?.style && !state.style.stale ? "Update style" : "Use this style"}</button></section>}</aside></article>; }

function OutputsView({ state, busy, onCreateOutput, onImages, onStoryboard, onCite }: { state: PersistedWorkshop | null; busy: boolean; onCreateOutput: (type: "deck" | "infographic") => Promise<void>; onImages: () => void; onStoryboard: () => void; onCite: (sourceId?: string) => void }) {
  const evidenceCount = state?.assetPlan?.evidenceClaimIds.length ?? state?.claims?.length ?? 0;
  const styleVersion = state?.style?.version;
  return <article className="outputs-view">
    <div className="outputs-heading"><div><p className="eyebrow">Deliver · approved work, not one-shot assets</p><h1>Outputs</h1><p>Every artifact inherits the approved brief, style, and active source scope.</p></div>{state?.outputs.some((output) => output.stale) && <span className="state waiting">Refresh needed</span>}</div>
    {!state?.briefApproved || !state.style || state.style.stale ? <section className="delivery-empty"><strong>Finish Shape first</strong><p>Approve the Map, then set Style. Deliverables appear when their inputs are ready.</p></section> : <>
      <section className="output-grid">{state.outputs.map((output) => <article className={`output-card ${output.stale ? "stale" : ""}`} key={output.id}><div className="artifact-preview"><iframe title={`${output.type} preview`} sandbox="allow-same-origin" src={`/api/workshop/artifacts/${output.id}`} /></div><div className="output-card-body"><div><span className={output.stale ? "state waiting" : "state current"}>{output.stale ? "Stale" : "Current"}</span><h2>{output.type === "deck" ? "Presentation" : "Infographic"}</h2><p>Brief v{state.frame?.version ?? 1} · Style v{styleVersion ?? 1} · {output.claimIds?.length ?? evidenceCount} cited claims</p></div><div><a className="text-link" href={`/api/workshop/artifacts/${output.id}`} target="_blank">Open artifact</a><button className="citation-chip" onClick={() => onCite(state?.claims?.find((claim) => output.claimIds?.includes(claim.id))?.sourceId)}>Source</button></div></div></article>)}</section>
      <section className="output-grid">{state.outputs.map((output) => <article className={`output-card ${output.stale ? "stale" : ""}`} key={output.id}><div className="artifact-preview"><iframe title={`${output.type} preview`} sandbox="allow-same-origin" src={`/api/workshop/artifacts/${output.id}`} /></div><div className="output-card-body"><div><span className={output.stale ? "state waiting" : "state current"}>{output.stale ? "Stale" : "Current"}</span><h2>{output.type === "deck" ? "Presentation" : "Infographic"}</h2><p>Brief v{state.frame?.version ?? 1} · Style v{styleVersion ?? 1} · {output.claimIds?.length ?? evidenceCount} cited claims</p></div><div><a className="text-link" href={`/api/workshop/artifacts/${output.id}`} target="_blank">Open artifact</a><button className="citation-chip" onClick={() => onCite(state?.claims?.find((claim) => output.claimIds?.includes(claim.id))?.sourceId)}>Source</button></div></div></article>)}{state?.videoState === "rendered" && <article className="output-card video-card"><div className="artifact-preview"><video controls src="/api/workshop/artifacts/video" /></div><div className="output-card-body"><div><span className="state current">Current</span><h2>Approved video</h2><p>Storyboard v{state.storyboard.version} · approved before render</p></div><a className="text-link" href="/api/workshop/artifacts/video" target="_blank">Open video</a></div></article>}</section>
      <section className="creation-row"><button disabled={busy} onClick={() => { void onCreateOutput("deck"); }}>Create presentation</button><button disabled={busy} onClick={() => { void onCreateOutput("infographic"); }}>Create infographic</button><button disabled={busy} onClick={onImages}>Plan image set</button><button disabled={busy} onClick={onStoryboard}>Open storyboard</button></section>
      {state.imageBatch && <section className="image-set"><div><h2>Image set</h2><p>Visual DNA v{state.imageBatch.id} · provider render not yet run</p></div><div className="contact-strip">{state.imageBatch.panels.map((panel, index) => <div className="image-tile" key={panel.id} style={{ "--tile": index } as React.CSSProperties}><span>{index + 1}</span><small>{panel.state === "planned" ? "Planned" : panel.state}</small></div>)}</div></section>}
      {state.storyboard.panels.length > 0 && <section className="storyboard-card"><div className="filmstrip">{state.storyboard.panels.map((panel, index) => <div className="film-frame" key={panel.id}><span>{index + 1}</span><strong>{panel.title}</strong><small>{panel.durationSeconds}s</small></div>)}</div><div><h2>Storyboard</h2><p>{state.storyboardApproved ? "Approved for video render" : "Editable · approval required before video"}</p></div></section>}
    </>}
  </article>;
}

function StoryboardView({ storyboard, approved, panel, busy, videoState, onSelect, onPost, onCite }: { storyboard?: PersistedWorkshop["storyboard"]; approved: boolean; panel?: PersistedWorkshop["storyboard"]["panels"][number]; busy: boolean; videoState?: PersistedWorkshop["videoState"]; onSelect: (id: string) => void; onPost: (body: Record<string, unknown>) => Promise<PersistedWorkshop | null>; onCite: (sourceId?: string) => void }) { const [title, setTitle] = useState(""); const [narration, setNarration] = useState(""); useEffect(() => { if (panel) { setTitle(panel.title); setNarration(panel.narration); } }, [panel?.id]); return <article className="storyboard-view"><div className="storyboard-heading"><div><p className="eyebrow">Deliver · editable before render</p><h1>Storyboard</h1><p>Change a panel, then approve the exact video you mean to ship.</p></div><span className={approved ? "state current" : "state waiting"}>{approved ? "Approved" : "Draft"}</span></div><div className="filmstrip">{(storyboard?.panels ?? []).map((item, index) => <button key={item.id} className={item.id === panel?.id ? "film-frame selected" : "film-frame"} onClick={() => onSelect(item.id)}><span>{index + 1}</span><strong>{item.title}</strong><small>{item.durationSeconds}s</small></button>)}</div>{panel && <section className="panel-editor"><div className="panel-visual"><span>{panel.title}</span></div><div className="panel-fields"><label>Panel title<input value={title} onChange={(event) => setTitle(event.target.value)} /></label><label>Narration<textarea value={narration} onChange={(event) => setNarration(event.target.value)} /></label><button className="secondary-button" disabled={busy} onClick={() => { void onPost({ action: "updateStoryboardPanel", panel: { id: panel.id, title, narration, durationSeconds: panel.durationSeconds } }); }}>Save panel</button><button className="citation-chip" onClick={() => onCite()}>Source</button></div></section>}{approved && <footer className="storyboard-footer"><button className="primary-button" disabled={busy || videoState === "queued" || videoState === "rendering"} onClick={() => { void onPost({ action: "renderVideo" }); }}>{videoState === "rendered" ? "Render again" : videoState === "queued" || videoState === "rendering" ? "Rendering…" : "Render approved storyboard"}</button></footer>}</article>; }

function SourcesSheet({ sources, activeIds, selected, onClose, onSelect, onToggle, onAdd, onCapture, onShowMap }: { sources: SourceItem[]; activeIds: string[]; selected: SourceItem | null; onClose: () => void; onSelect: (source: SourceItem) => void; onToggle: (id: string) => void; onAdd: () => void; onCapture: () => void; onShowMap: (source: SourceItem) => void }) { const active = selected ?? sources[0]; return <Sheet title={`Sources · ${activeIds.length} of ${sources.length} grounding`} kind="sources" onClose={onClose}><p className="sheet-intro">Checked sources ground the Map and every new deliverable. Changing scope marks dependent work for review.</p><div className="sheet-actions"><button className="secondary-button" onClick={onAdd}>Add source</button><button className="secondary-button" onClick={onCapture}>Capture transcript</button></div><div className="source-list">{sources.map((source) => <div className={active?.id === source.id ? "source-item active" : "source-item"} key={source.id}><input aria-label={`Use ${source.title} for grounding`} type="checkbox" checked={activeIds.includes(source.id)} onChange={() => onToggle(source.id)} /><button onClick={() => onSelect(source)}><span>{source.type}</span><div><strong>{source.title}</strong><small>{source.origin} · {source.claimCount} claims</small></div></button></div>)}</div>{active && <article className="source-preview"><strong>{active.title}</strong><p>“{active.excerpt}”</p><small>{active.locator}</small><button className="text-button" onClick={() => onShowMap(active)}>Show on Map</button></article>}</Sheet>; }

function LibrarySheet({ state, canDeliver, onClose, onOpen }: { state: PersistedWorkshop | null; canDeliver: boolean; onClose: () => void; onOpen: (view: ObjectView) => void }) { return <Sheet title="Workshop library" kind="library" onClose={onClose}><p className="sheet-intro">One Workshop, one grounded work system.</p><section className="library-group"><span>Capture</span><button onClick={() => onOpen("map")}>Sources and Map <small>{state?.activeSourceIds.length ?? 0} active sources</small></button></section><section className="library-group"><span>Shape</span><button disabled={!state?.briefApproved} onClick={() => onOpen("brief")}>Approved brief <small>{state?.frame?.stale ? "Needs review" : state?.frame ? "Current" : "Not ready"}</small></button></section><section className="library-group"><span>Deliver</span><button disabled={!canDeliver} onClick={() => onOpen("outputs")}>Outputs <small>{state?.outputs.length ?? 0} artifacts</small></button><button disabled={!canDeliver} onClick={() => onOpen("storyboard")}>Storyboard <small>{state?.storyboard.panels.length ?? 0} panels</small></button></section></Sheet>; }
function DetailsSheet({ state, node, onClose, onExtract }: { state: PersistedWorkshop | null; node?: MapNode; onClose: () => void; onExtract: () => void }) { return <Sheet title="Details" onClose={onClose}><dl className="detail-list"><dt>Selected claim</dt><dd>{node ? node.locator : "Select a Map note"}</dd><dt>Scope</dt><dd>{state?.activeSourceIds.length ?? 0} active sources</dd><dt>Privacy</dt><dd>Sanitized local fixture</dd></dl><div className="sheet-actions"><button className="secondary-button" onClick={onExtract}>Extract candidates</button></div></Sheet>; }
function AddSourceSheet({ onClose, onPost }: { onClose: () => void; onPost: (body: Record<string, unknown>) => Promise<PersistedWorkshop | null> }) { const [title, setTitle] = useState(""); const [text, setText] = useState(""); return <Sheet title="Add a source" kind="sources" onClose={onClose}><p className="sheet-intro">Add material you are allowed to use. It becomes local, cited evidence.</p><label className="form-field">Title<input value={title} onChange={(event) => setTitle(event.target.value)} /></label><label className="form-field">Paste text<textarea value={text} onChange={(event) => setText(event.target.value)} /></label><button className="primary-button" disabled={!title.trim() || !text.trim()} onClick={() => { void onPost({ action: "ingestSource", source: { title, origin: "Local sanitized note", text, permission: "sanitized" } }).then((next) => next && onClose()); }}>Add to Map</button></Sheet>; }
function CaptureSheet({ onClose, onPost }: { onClose: () => void; onPost: (body: Record<string, unknown>) => Promise<PersistedWorkshop | null> }) { const [text, setText] = useState(""); return <Sheet title="Capture transcript" kind="sources" onClose={onClose}><p className="sheet-intro">Capture-only fallback for durable local evidence. It is not a second chat composer.</p><label className="form-field">Transcript segment<textarea value={text} onChange={(event) => setText(event.target.value)} /></label><button className="primary-button" disabled={!text.trim()} onClick={() => { void onPost({ action: "captureFallbackTranscript", text }).then((next) => next && onClose()); }}>Capture to Workshop</button></Sheet>; }
function Sheet({ title, kind, onClose, children }: { title: string; kind?: "sources" | "library"; onClose: () => void; children: ReactNode }) { return <aside className={`side-sheet ${kind === "sources" ? "sources-sheet" : ""}`}><header><h2>{title}</h2><button className="close-button" onClick={onClose} aria-label="Close">×</button></header>{children}</aside>; }
