"use client";

import React, { useEffect, useMemo, useState, type ReactNode } from "react";

type ObjectView = "map" | "brief" | "outputs" | "storyboard";
type Sheet = "sources" | "evidence" | "add-source" | null;
type SourceItem = { id: string; type: "TXT" | "PDF" | "WEB"; title: string; origin: string; claimCount: number; excerpt: string; locator: string; permission: "private" | "sanitized" | "shareable" };
type MapNode = { id: string; title: string; body: string; kind: "grounded" | "derived" | "creative"; locator: string; sourceId?: string; x: number; y: number };
type ManualStylePayload = { name: string; accent: string; ink: string; paper: string; logos: string[]; licensedFonts: string[]; references: string[]; negativeRules: string[]; intentProfile: "client_facing_pitch" | "board_deck" | "internal_workshop" };
type PersistedWorkshop = { title: string; briefApproved: boolean; storyboardApproved: boolean; videoState: "blocked" | "queued" | "rendering" | "rendered"; sourceItems: SourceItem[]; activeSourceIds: string[]; sourceChunks?: { id: string; sourceId: string; text: string; locator: string }[]; claims?: { id: string; sourceId: string; chunkId: string; text: string; locator: string }[]; candidates?: { id: string; category: string; text: string; locator: string }[]; mapNodes: MapNode[]; mapEdges?: { id: string; from: string; to: string; kind: string; label?: string }[]; frame?: { version: number; markdown: string; stale: boolean }; style?: { version: number; name: string; accent: string; ink: string; paper: string; stale: boolean }; assetPlan?: { version: number; stale: boolean; evidenceClaimIds: string[] }; storyboard: { version: number; stale: boolean; panels: { id: string; title: string; narration: string; durationSeconds: number; approved: boolean; stale: boolean }[] }; imageBatch?: { id: string; stale: boolean; panels: { id: string; version: number; prompt: string; state: "planned" | "selected_for_regeneration" | "failed" }[] }; outputs: { id: string; type: "deck" | "infographic"; stale: boolean; artifactPath: string; claimIds?: string[] }[] };
export default function WorkshopPage() {
  const [state, setState] = useState<PersistedWorkshop | null>(null); const [view, setView] = useState<ObjectView>("map"); const [sheet, setSheet] = useState<Sheet>(null);
  const [selectedNodeId, setSelectedNodeId] = useState(""); const [selectedSource, setSelectedSource] = useState<SourceItem | null>(null); const [selectedPanelId, setSelectedPanelId] = useState(""); const [notice, setNotice] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  useEffect(() => { void reload(); }, []);
  const selectedNode = useMemo(() => state?.mapNodes.find((node) => node.id === selectedNodeId), [state, selectedNodeId]);
  const selectedPanel = useMemo(() => state?.storyboard.panels.find((panel) => panel.id === selectedPanelId) ?? state?.storyboard.panels[0], [state, selectedPanelId]);
  const canDeliver = Boolean(state?.briefApproved && state.style && !state.style.stale);
  const currentTitle: Record<ObjectView, string> = { map: "Map", brief: "Brief", outputs: "Outputs", storyboard: "Storyboard" };
  async function reload() { const response = await fetch("/api/workshop"); if (response.ok) setState(await response.json() as PersistedWorkshop); }
  async function post(body: Record<string, unknown>) { setBusy(true); setNotice(null); try { const response = await fetch("/api/workshop", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) }); const next = await response.json() as PersistedWorkshop & { error?: string }; if (!response.ok) throw new Error(next.error ?? "Workshop action failed"); setState(next); return next; } catch (error) { setNotice(error instanceof Error ? error.message : "Workshop action failed"); return null; } finally { setBusy(false); } }
  function open(next: ObjectView) { setView(next); setSheet(null); }
  function cite(sourceId?: string) { const source = state?.sourceItems.find((item) => item.id === sourceId) ?? state?.sourceItems[0] ?? null; setSelectedSource(source); setSheet("evidence"); }
  async function generatePackage() { if (!state?.outputs.some((output) => output.type === "deck" && !output.stale)) await post({ action: "generateOutput", outputType: "deck" }); if (!state?.outputs.some((output) => output.type === "infographic" && !output.stale)) await post({ action: "generateOutput", outputType: "infographic" }); if (!state?.imageBatch || state.imageBatch.stale) await post({ action: "createImageBatch" }); await post({ action: "generateAssetPlan" }); await post({ action: "generateStoryboard" }); setNotice("Package created from the approved brief, Style, and active source scope."); open("outputs"); }
  return <main className="workshop-shell">
    <header className="workshop-header"><div className="header-title"><button className="back-button" aria-label="Back to Map" disabled={view === "map"} onClick={() => open("map")}>‹</button><div className="object-title"><strong>WorkshopLM</strong><span>{currentTitle[view]}</span><small>{view === "map" ? "Evidence becomes structure" : view === "brief" ? "Approved production contract" : view === "outputs" ? "Coherent delivery package" : "Editable before render"}</small></div></div><div className="header-actions"><button className="source-scope" onClick={() => setSheet("sources")}><span>{state?.activeSourceIds.length ?? 0} sources</span><small>Grounding this Workshop</small></button>{view === "map" && (state?.briefApproved && !state.frame?.stale ? <button className="primary-button" onClick={() => open("brief")}>Review approved brief</button> : <button className="primary-button" disabled={busy || !state?.mapNodes.length} onClick={() => { void post({ action: "approveBrief" }).then((next) => next && open("brief")); }}>Approve brief</button>)}{view === "brief" && canDeliver && <button className="primary-button" onClick={() => open("outputs")}>Open package</button>}{view === "outputs" && (state?.storyboard?.panels.length ?? 0) > 0 && <button className="primary-button" onClick={() => open("storyboard")}>Open storyboard</button>}{view === "storyboard" && <button className="primary-button" disabled={busy || Boolean(state?.storyboardApproved) || Boolean(state?.storyboard.stale)} onClick={() => { void post({ action: "approveStoryboard" }); }}>{state?.storyboardApproved ? "Storyboard approved" : "Approve storyboard"}</button>}</div></header>
    {notice && <div className="notice" role="status"><span>{notice}</span><button onClick={() => setNotice(null)} aria-label="Dismiss">×</button></div>}
    <section className="object-canvas" aria-label={currentTitle[view]}>{view === "map" && <MapCanvas state={state} selectedNode={selectedNode} busy={busy} onSelect={setSelectedNodeId} onSync={(canvasNodes) => { void post({ action: "syncMapCanvas", canvasNodes }); }} onCite={cite} onApprove={() => { void post({ action: "approveBrief" }).then((next) => next && open("brief")); }} />}{view === "brief" && <BriefView state={state} busy={busy} onPost={post} onCite={cite} />}{view === "outputs" && <OutputsView state={state} busy={busy} onGeneratePackage={() => { void generatePackage(); }} onCite={cite} />}{view === "storyboard" && <StoryboardView storyboard={state?.storyboard} approved={Boolean(state?.storyboardApproved)} panel={selectedPanel} busy={busy} videoState={state?.videoState} onSelect={setSelectedPanelId} onPost={post} onCite={cite} />}</section>
    {sheet === "sources" && <SourcesSheet sources={state?.sourceItems ?? []} activeIds={state?.activeSourceIds ?? []} selected={selectedSource} onClose={() => setSheet(null)} onSelect={setSelectedSource} onToggle={(sourceId) => { const current = state?.activeSourceIds ?? []; const next = current.includes(sourceId) ? current.filter((id) => id !== sourceId) : [...current, sourceId]; void post({ action: "setActiveSourceScope", sourceIds: next }); }} onAdd={() => setSheet("add-source")} onShowMap={(source) => { setSelectedNodeId(state?.mapNodes.find((node) => node.sourceId === source.id)?.id ?? ""); open("map"); }} />}
    {sheet === "evidence" && selectedSource && <EvidenceSheet source={selectedSource} onClose={() => setSheet(null)} onShowMap={() => { setSelectedNodeId(state?.mapNodes.find((node) => node.sourceId === selectedSource.id)?.id ?? ""); open("map"); }} />}{sheet === "add-source" && <AddSourceSheet onClose={() => setSheet("sources")} onPost={post} />}
  </main>;
}

function MapCanvas({ state, selectedNode, busy, onSelect, onSync, onCite, onApprove }: { state: PersistedWorkshop | null; selectedNode?: MapNode; busy: boolean; onSelect: (id: string) => void; onSync: (nodes: Pick<MapNode, "id" | "title" | "x" | "y">[]) => void; onCite: (sourceId?: string) => void; onApprove: () => void }) {
  const sources = (state?.sourceItems ?? []).filter((source) => state?.activeSourceIds.includes(source.id));
  const nodes = (state?.mapNodes ?? []).filter((node) => !node.sourceId || state?.activeSourceIds.includes(node.sourceId));
  const grounded = nodes.filter((node) => node.kind === "grounded");
  const implications = nodes.filter((node) => node.kind !== "grounded");
  const positioned = new Map<string, { x: number; y: number }>();
  sources.forEach((source, index) => positioned.set(`source:${source.id}`, { x: 11, y: 25 + index * (50 / Math.max(1, sources.length - 1)) }));
  grounded.forEach((node, index) => positioned.set(node.id, { x: 43, y: 28 + index * (48 / Math.max(1, grounded.length - 1)) }));
  implications.forEach((node, index) => positioned.set(node.id, { x: 72, y: 31 + index * (38 / Math.max(1, implications.length - 1)) }));
  const relatedSourceId = (node: MapNode, index: number) => node.sourceId ?? sources[index % Math.max(1, sources.length)]?.id;
  const selectedSourceId = selectedNode ? relatedSourceId(selectedNode, Math.max(0, nodes.indexOf(selectedNode))) : undefined;
  const source = sources.find((item) => item.id === selectedSourceId);
  const isRelatedNode = (node: MapNode) => !selectedNode || node.id === selectedNode.id || (selectedNode.kind !== "grounded" && node.kind === "grounded") || (selectedNode.kind === "grounded" && node.kind !== "grounded");
  return <div className={`map-canvas ${selectedNode ? "tracing" : ""}`}>
    <div className="map-caption"><span className="desktop-label">Map · source → claim → decision</span><span className="mobile-label">Evidence outline</span><small>{nodes.length} claims from {sources.length} active sources</small></div>
    <div className="map-cluster source-cluster"><span>Sources</span></div><div className="map-cluster claim-cluster"><span>Grounded claims</span></div><div className="map-cluster decision-cluster"><span>Implications</span></div>
    <svg className="relationship-lines" viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true">
      {grounded.map((node, index) => { const from = positioned.get(`source:${relatedSourceId(node, index)}`); const to = positioned.get(node.id); return from && to ? <path key={`source-${node.id}`} className={selectedNode && selectedNode.id !== node.id && selectedSourceId !== relatedSourceId(node, index) ? "dim" : selectedNode ? "active" : ""} d={`M ${from.x + 7} ${from.y} C 27 ${from.y}, 28 ${to.y}, ${to.x - 9} ${to.y}`} /> : null; })}
      {implications.map((node, index) => { const fromNode = grounded[index % Math.max(1, grounded.length)]; const from = fromNode && positioned.get(fromNode.id); const to = positioned.get(node.id); return from && to ? <path key={`claim-${node.id}`} className={selectedNode && selectedNode.id !== node.id && selectedNode.id !== fromNode.id ? "dim" : selectedNode ? "active" : ""} d={`M ${from.x + 9} ${from.y} C 56 ${from.y}, 57 ${to.y}, ${to.x - 9} ${to.y}`} /> : null; })}
    </svg>
    {sources.map((item) => { const point = positioned.get(`source:${item.id}`)!; const active = !selectedNode || item.id === selectedSourceId; return <button key={item.id} className={`source-anchor ${active ? "path-active" : "path-dim"}`} style={{ left: `${point.x}%`, top: `${point.y}%` }} onClick={() => onCite(item.id)}><span>{item.type}</span><strong>{item.title}</strong><small>{item.claimCount} claims</small></button>; })}
    {nodes.map((node) => { const point = positioned.get(node.id)!; return <button key={node.id} className={`map-note ${node.kind} ${selectedNode?.id === node.id ? "selected-note" : ""} ${isRelatedNode(node) ? "path-active" : "path-dim"}`} style={{ left: `${point.x}%`, top: `${point.y}%` }} onClick={() => onSelect(selectedNode?.id === node.id ? "" : node.id)}><span>{node.kind === "grounded" ? "Verified claim" : node.kind}</span><strong>{node.title}</strong><p>{node.body}</p><small>{node.locator}</small></button>; })}
    {selectedNode && <ClaimInspector node={selectedNode} source={source} busy={busy} onClose={() => onSelect("")} onSave={(title) => onSync([{ id: selectedNode.id, title, x: selectedNode.x, y: selectedNode.y }])} onOpenSource={() => onCite(selectedSourceId)} />}
    {!selectedNode && <section className="approval-card"><div><span>Brief gate</span><strong>{state?.briefApproved && state.frame && !state.frame.stale ? `Approved · Brief v${state.frame.version}` : "Ready for review"}</strong><p>{grounded.length} grounded · {implications.filter((node) => node.kind === "derived").length} derived · {sources.length} sources</p></div>{state?.briefApproved && state.frame && !state.frame.stale ? <span className="approval-seal">Approved</span> : <button className="primary-button" disabled={busy || nodes.length === 0} onClick={onApprove}>Approve as brief</button>}</section>}
  </div>;
}

function ClaimInspector({ node, source, busy, onClose, onSave, onOpenSource }: { node: MapNode; source?: SourceItem; busy: boolean; onClose: () => void; onSave: (title: string) => void; onOpenSource: () => void }) { const [title, setTitle] = useState(node.title); useEffect(() => setTitle(node.title), [node.id, node.title]); return <aside className="claim-inspector"><header><div><span>Evidence path</span><strong>{node.kind === "grounded" ? "Verified claim" : node.kind}</strong></div><button aria-label="Close evidence" onClick={onClose}>×</button></header><label>Claim<input value={title} onChange={(event) => setTitle(event.target.value)} /></label><blockquote>{source?.excerpt ?? node.body}</blockquote><p className="source-locator">{source?.locator ?? node.locator}</p><div className="inspector-actions"><button className="secondary-button" disabled={busy || title.trim() === node.title || !title.trim()} onClick={() => onSave(title.trim())}>Save claim</button><button className="text-button" onClick={onOpenSource}>Open source</button></div></aside>; }

function BriefView({ state, busy, onPost, onCite }: { state: PersistedWorkshop | null; busy: boolean; onPost: (body: Record<string, unknown>) => Promise<PersistedWorkshop | null>; onCite: (sourceId?: string) => void }) {
  const [name, setName] = useState(state?.style?.name ?? "WorkshopLM editorial"); const [accent, setAccent] = useState(state?.style?.accent ?? "#1668E3");
  const locked = Boolean(state?.style && !state.style.stale);
  const lock = () => { const style: ManualStylePayload = { name, accent, ink: "#0D0D0D", paper: "#FFFFFF", logos: [], licensedFonts: ["system-ui"], references: ["calm editorial work surface"], negativeRules: ["no decorative gradients"], intentProfile: "client_facing_pitch" }; void onPost({ action: "lockManualStyle", manualStyle: style }); };
  return <article className="brief-view"><section className="brief-document"><div className="approval-receipt"><span>Approved brief · v{state?.frame?.version ?? 1}</span><strong>{state?.activeSourceIds.length ?? 0} sources · {state?.mapNodes.filter((node) => node.kind === "grounded").length ?? 0} grounded · {state?.mapNodes.filter((node) => node.kind === "derived").length ?? 0} derived</strong><small>Downstream input: package, storyboard, and rendered video</small></div><p className="eyebrow">Production contract</p><h1>Turn raw thinking into finished, traceable work.</h1><p className="document-intro">The approved Map is now a versioned brief. Every deliverable must preserve its active source scope and evidence path.</p><pre>{state?.frame?.markdown ?? "No approved brief yet."}</pre><div className="brief-citations">{state?.claims?.slice(0, 3).map((claim) => <button className="citation-chip document-citation" key={claim.id} onClick={() => onCite(claim.sourceId)}>{claim.locator}</button>)}</div></section><aside className={`style-contract ${locked ? "locked" : ""}`}><div className="style-contract-heading"><div><span>Visual contract</span><h2>{locked ? `Style v${state?.style?.version ?? 1} locked` : "Lock one coherent system"}</h2></div>{locked && <span className="approval-seal">Locked</span>}</div><label>Style name<input value={name} onChange={(event) => setName(event.target.value)} /></label><label>Accent<input value={accent} onChange={(event) => setAccent(event.target.value)} /></label><div className="palette-preview"><i style={{ background: accent }} /><i style={{ background: "#0D0D0D" }} /><i style={{ background: "#FFFFFF" }} /></div><div className="type-preview"><strong>Aa</strong><span>System sans · decisive hierarchy</span></div><div className="mini-output-previews"><i style={{ "--accent": accent } as React.CSSProperties} /><i style={{ "--accent": accent } as React.CSSProperties} /><i style={{ "--accent": accent } as React.CSSProperties} /></div><button className="primary-button" disabled={busy} onClick={lock}>{locked ? "Update Style v1" : "Lock Style v1"}</button><small>Palette, typography, image treatment, and density propagate to every artifact.</small></aside></article>;
}

function OutputsView({ state, busy, onGeneratePackage, onCite }: { state: PersistedWorkshop | null; busy: boolean; onGeneratePackage: () => void; onCite: (sourceId?: string) => void }) {
  const evidenceCount = state?.assetPlan?.evidenceClaimIds.length ?? state?.claims?.length ?? 0;
  const styleVersion = state?.style?.version;
  return <article className="outputs-view">
    <div className="outputs-heading"><div><p className="eyebrow">Coherent delivery package</p><h1>One system. Every format.</h1><p>Brief v{state?.frame?.version ?? 1} · Style v{styleVersion ?? 1} · {state?.activeSourceIds.length ?? 0} active sources</p></div><div className="package-actions">{state?.outputs.some((output) => output.stale) && <span className="state waiting">Refresh needed</span>}<button className="primary-button" disabled={busy} onClick={onGeneratePackage}>{state?.outputs.length ? "Refresh package" : "Generate package"}</button></div></div>
    {!state?.briefApproved || !state.style || state.style.stale ? <section className="delivery-empty"><strong>Finish Shape first</strong><p>Approve the Map, then set Style. Deliverables appear when their inputs are ready.</p></section> : <>
      <section className="output-grid">{state.outputs.map((output) => <article className={`output-card ${output.type} ${output.stale ? "stale" : ""}`} key={output.id}><div className="artifact-preview"><iframe title={`${output.type} preview`} sandbox="allow-same-origin" src={`/api/workshop/artifacts/${output.id}`} /></div><div className="output-card-body"><div><span className={output.stale ? "state waiting" : "state current"}>{output.stale ? "Stale" : `Style v${styleVersion ?? 1}`}</span><h2>{output.type === "deck" ? "Presentation" : "Evidence infographic"}</h2><p>{output.claimIds?.length ?? evidenceCount} cited claims · Brief v{state.frame?.version ?? 1}</p></div><div><a className="text-link" href={`/api/workshop/artifacts/${output.id}`} target="_blank">Open</a><button className="citation-chip" onClick={() => onCite(state?.claims?.find((claim) => output.claimIds?.includes(claim.id))?.sourceId)}>Trace</button></div></div></article>)}{state?.videoState === "rendered" && <article className="output-card video-card"><div className="artifact-preview"><video controls src="/api/workshop/artifacts/video" /></div><div className="output-card-body"><div><span className="state current">Approved render</span><h2>Demo video</h2><p>Storyboard v{state.storyboard.version} · gated before render</p></div><a className="text-link" href="/api/workshop/artifacts/video" target="_blank">Open</a></div></article>}</section>
      {state.imageBatch && <section className="image-set"><div><span className="state waiting">Provider render pending</span><h2>Coherent image set</h2><p>Locked palette and art direction · {state.imageBatch.panels.length} planned frames</p></div><div className="contact-strip">{state.imageBatch.panels.map((panel, index) => <div className="image-tile" key={panel.id} style={{ "--tile": index } as React.CSSProperties}><span>{String(index + 1).padStart(2, "0")}</span><small>{panel.state === "planned" ? "Planned" : panel.state}</small></div>)}</div></section>}
      {state.storyboard.panels.length > 0 && <section className="storyboard-card"><div className="filmstrip">{state.storyboard.panels.map((panel, index) => <div className="film-frame" key={panel.id}><span>{index + 1}</span><strong>{panel.title}</strong><small>{panel.durationSeconds}s</small></div>)}</div><div><h2>Storyboard</h2><p>{state.storyboardApproved ? "Approved for video render" : "Editable · approval required before video"}</p></div></section>}
    </>}
  </article>;
}

function StoryboardView({ storyboard, approved, panel, busy, videoState, onSelect, onPost, onCite }: { storyboard?: PersistedWorkshop["storyboard"]; approved: boolean; panel?: PersistedWorkshop["storyboard"]["panels"][number]; busy: boolean; videoState?: PersistedWorkshop["videoState"]; onSelect: (id: string) => void; onPost: (body: Record<string, unknown>) => Promise<PersistedWorkshop | null>; onCite: (sourceId?: string) => void }) {
  const [title, setTitle] = useState(""); const [narration, setNarration] = useState(""); useEffect(() => { if (panel) { setTitle(panel.title); setNarration(panel.narration); } }, [panel?.id]);
  const duration = (storyboard?.panels ?? []).reduce((sum, item) => sum + item.durationSeconds, 0);
  return <article className="storyboard-view"><div className="storyboard-heading"><div><p className="eyebrow">Editable before the expensive step</p><h1>Storyboard v{storyboard?.version ?? 1}</h1><p>Every panel carries the approved brief and Style contract into the render.</p></div><span className={approved ? "state current" : "state waiting"}>{approved ? "Approved for render" : "Draft"}</span></div><div className="filmstrip">{(storyboard?.panels ?? []).map((item, index) => <button key={item.id} className={item.id === panel?.id ? "film-frame selected" : "film-frame"} style={{ "--panel": index } as React.CSSProperties} onClick={() => onSelect(item.id)}><span>{String(index + 1).padStart(2, "0")}</span><strong>{item.title}</strong><small>{item.durationSeconds}s · cited</small></button>)}</div>{panel && <section className="panel-editor"><div className="panel-visual" style={{ "--panel": Math.max(0, storyboard?.panels.findIndex((item) => item.id === panel.id) ?? 0) } as React.CSSProperties}><small>Panel preview</small><span>{panel.title}</span><p>{panel.narration}</p></div><div className="panel-fields"><span className="state current">Grounded panel</span><label>Panel title<input value={title} onChange={(event) => setTitle(event.target.value)} /></label><label>Narration<textarea value={narration} onChange={(event) => setNarration(event.target.value)} /></label><div className="inspector-actions"><button className="secondary-button" disabled={busy} onClick={() => { void onPost({ action: "updateStoryboardPanel", panel: { id: panel.id, title, narration, durationSeconds: panel.durationSeconds } }); }}>Save panel</button><button className="citation-chip" onClick={() => onCite()}>Trace source</button></div></div></section>}<footer className="storyboard-gate"><div><span>Storyboard gate</span><strong>{storyboard?.panels.length ?? 0} panels · {duration}s · narration complete</strong><p>{storyboard?.panels.length ?? 0} of {storyboard?.panels.length ?? 0} panels grounded · Brief and Style current</p></div>{approved ? <button className="primary-button" disabled={busy || videoState === "queued" || videoState === "rendering"} onClick={() => { void onPost({ action: "renderVideo" }); }}>{videoState === "rendered" ? "Render again" : videoState === "queued" || videoState === "rendering" ? "Rendering…" : "Prepare render"}</button> : <span className="approval-seal">Awaiting approval</span>}</footer></article>;
}

function SourcesSheet({ sources, activeIds, selected, onClose, onSelect, onToggle, onAdd, onShowMap }: { sources: SourceItem[]; activeIds: string[]; selected: SourceItem | null; onClose: () => void; onSelect: (source: SourceItem) => void; onToggle: (id: string) => void; onAdd: () => void; onShowMap: (source: SourceItem) => void }) { const active = selected ?? sources[0]; return <Sheet title={`Sources · ${activeIds.length} of ${sources.length} active`} kind="sources" onClose={onClose}><p className="sheet-intro">This scope grounds the Map and every artifact. Changing it marks dependent work for review.</p><div className="sheet-actions"><button className="secondary-button" onClick={onAdd}>Add source</button></div><div className="source-list">{sources.map((source) => <div className={active?.id === source.id ? "source-item active" : "source-item"} key={source.id}><input aria-label={`Use ${source.title} for grounding`} type="checkbox" checked={activeIds.includes(source.id)} onChange={() => onToggle(source.id)} /><button onClick={() => onSelect(source)}><span>{source.type}</span><div><strong>{source.title}</strong><small>{source.origin} · {source.claimCount} claims</small></div></button></div>)}</div>{active && <article className="source-preview"><strong>{active.title}</strong><p>“{active.excerpt}”</p><small>{active.locator}</small><button className="text-button" onClick={() => onShowMap(active)}>Highlight on Map</button></article>}</Sheet>; }

function EvidenceSheet({ source, onClose, onShowMap }: { source: SourceItem; onClose: () => void; onShowMap: () => void }) { return <Sheet title="Evidence" onClose={onClose}><span className="state current">Exact source</span><blockquote className="evidence-quote">“{source.excerpt}”</blockquote><p className="source-locator">{source.locator}</p><dl className="evidence-meta"><dt>Source</dt><dd>{source.title}</dd><dt>Origin</dt><dd>{source.origin}</dd><dt>Permission</dt><dd>{source.permission}</dd></dl><button className="primary-button" onClick={onShowMap}>Illuminate path on Map</button></Sheet>; }
function AddSourceSheet({ onClose, onPost }: { onClose: () => void; onPost: (body: Record<string, unknown>) => Promise<PersistedWorkshop | null> }) { const [title, setTitle] = useState(""); const [text, setText] = useState(""); return <Sheet title="Add a source" kind="sources" onClose={onClose}><p className="sheet-intro">Add material you are allowed to use. It becomes local, cited evidence.</p><label className="form-field">Title<input value={title} onChange={(event) => setTitle(event.target.value)} /></label><label className="form-field">Paste text<textarea value={text} onChange={(event) => setText(event.target.value)} /></label><button className="primary-button" disabled={!title.trim() || !text.trim()} onClick={() => { void onPost({ action: "ingestSource", source: { title, origin: "Local sanitized note", text, permission: "sanitized" } }).then((next) => next && onClose()); }}>Add to Map</button></Sheet>; }
function Sheet({ title, kind, onClose, children }: { title: string; kind?: "sources"; onClose: () => void; children: ReactNode }) { return <aside className={`side-sheet ${kind === "sources" ? "sources-sheet" : ""}`}><header><h2>{title}</h2><button className="close-button" onClick={onClose} aria-label="Close">×</button></header>{children}</aside>; }
