"use client";

import { useEffect, useMemo, useState } from "react";
import dynamic from "next/dynamic";

type ObjectView = "map" | "brief" | "design" | "sketch" | "storyboard" | "trace";
type Sheet = "sources" | "library" | "details" | "capture" | "add-source" | null;
type SourceItem = { id: string; type: "TXT" | "PDF" | "WEB"; title: string; origin: string; claimCount: number; excerpt: string; locator: string; permission: "private" | "sanitized" | "shareable" };
type MapNode = { id: string; title: string; body: string; kind: "grounded" | "derived" | "creative"; locator: string; sourceId?: string; x: number; y: number };
type ManualStylePayload = { name: string; accent: string; ink: string; paper: string; logos: string[]; licensedFonts: string[]; references: string[]; negativeRules: string[]; intentProfile: "client_facing_pitch" | "board_deck" | "internal_workshop" };
type PersistedWorkshop = {
  briefApproved: boolean; storyboardApproved: boolean; videoState: "blocked" | "queued" | "rendering" | "rendered";
  firstTranscriptAt?: string; firstRenderedOutputAt?: string; sourceItems: SourceItem[]; sourceChunks?: { id: string; sourceId: string; text: string; locator: string }[];
  claims?: { id: string; sourceId: string; chunkId: string; text: string; locator: string }[]; candidates?: { id: string; category: string; text: string; locator: string }[];
  mapNodes: MapNode[]; mapEdges?: { id: string; from: string; to: string; kind: string; label?: string }[];
  frame?: { version: number; markdown: string; markdownPath: string; executablePath: string; stale: boolean };
  style?: { version: number; name: string; accent: string; ink: string; paper: string; references: string[]; negativeRules: string[]; intentProfile: string; stale: boolean };
  visualDna?: { version: number; palette: { accent: string; ink: string; paper: string }; approved: boolean; stale: boolean };
  sketch?: { version: number; graphRevision: number; nodes: Omit<MapNode, "x" | "y">[]; stale: boolean; approved: boolean };
  assetPlan?: { version: number; stale: boolean; items: { id: string; outputType: string; title: string; locator: string }[] };
  storyboard: { version: number; stale: boolean; panels: { id: string; title: string; narration: string; durationSeconds: number; approved: boolean; stale: boolean }[] };
  imageBatch?: { id: string; stale: boolean; panels: { id: string; version: number; prompt: string; state: "planned" | "selected_for_regeneration" | "failed"; error?: string }[] };
  outputs: { id: string; type: "deck" | "infographic"; stale: boolean; artifactPath: string }[];
};
const ExcalidrawMap = dynamic<{ nodes: MapNode[]; editable: boolean; onSync: (nodes: Pick<MapNode, "id" | "title" | "x" | "y">[]) => void }>(() => import("./excalidraw-map.js").then((module) => module.ExcalidrawMap), { ssr: false });

export default function WorkshopPage() {
  const [state, setState] = useState<PersistedWorkshop | null>(null);
  const [view, setView] = useState<ObjectView>("map");
  const [sheet, setSheet] = useState<Sheet>(null);
  const [selectedNodeId, setSelectedNodeId] = useState("");
  const [selectedSource, setSelectedSource] = useState<SourceItem | null>(null);
  const [selectedPanelId, setSelectedPanelId] = useState("");
  const [mapEditing, setMapEditing] = useState(false);
  const [notice, setNotice] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);

  useEffect(() => { void reload(); }, []);
  const selectedNode = useMemo(() => state?.mapNodes.find((node) => node.id === selectedNodeId), [state, selectedNodeId]);
  const selectedPanel = useMemo(() => state?.storyboard.panels.find((panel) => panel.id === selectedPanelId) ?? state?.storyboard.panels[0], [state, selectedPanelId]);
  const currentTitle: Record<ObjectView, string> = { map: "Map", brief: "Brief", design: "Style", sketch: "Sketch", storyboard: "Storyboard", trace: "Evidence trace" };
  const canCreate = Boolean(state?.briefApproved && state.style && !state.style.stale);

  async function reload() {
    const response = await fetch("/api/workshop");
    if (response.ok) setState(await response.json() as PersistedWorkshop);
  }
  async function post(body: Record<string, unknown>) {
    setBusy(true); setNotice(null);
    try {
      const response = await fetch("/api/workshop", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) });
      const next = await response.json() as PersistedWorkshop & { error?: string };
      if (!response.ok) throw new Error(next.error ?? "Workshop action failed");
      setState(next); return next;
    } catch (error) {
      setNotice(error instanceof Error ? error.message : "Workshop action failed"); return null;
    } finally { setBusy(false); }
  }
  function open(view: ObjectView) { setView(view); setSheet(null); setMapEditing(false); }
  async function approveMap() { const next = await post({ action: "approveBrief" }); if (next) open("brief"); }
  async function syncMapCanvas(nodes: Pick<MapNode, "id" | "title" | "x" | "y">[]) { await post({ action: "syncMapCanvas", canvasNodes: nodes }); }
  async function createOutput(outputType: "deck" | "infographic") { const next = await post({ action: "generateOutput", outputType }); if (next) { setNotice(`${outputType === "deck" ? "Deck" : "Infographic"} created from the current brief and style.`); setSheet("library"); } }
  async function createStoryboard() { const next = await post({ action: "generateStoryboard" }); if (next) open("storyboard"); }
  async function renderVideo() { const next = await post({ action: "renderVideo" }); if (next) setNotice("Render queued. It will use the approved current storyboard."); }

  return <main className="workshop-shell">
    <header className="workshop-header">
      <div className="header-title"><button className="back-button" aria-label="Back to Map" disabled={view === "map"} onClick={() => open("map")}>‹</button><button className="object-title" aria-expanded={sheet === "library"} onClick={() => setSheet("library")}>WorkshopLM <span>/</span> {currentTitle[view]} <i>⌄</i></button></div>
      <div className="header-actions"><button className="text-button host-return" onClick={() => window.parent.focus()}>Continue in ChatGPT</button><button className="text-button" onClick={() => setSheet("sources")}>Sources <strong>{state?.sourceItems.length ?? 0}</strong></button><button className="icon-only" aria-label="Workshop details" onClick={() => setSheet("details")}>•••</button>{view === "map" && <button className="primary-button" disabled={busy || !state?.mapNodes.length} onClick={() => { void approveMap(); }}>{state?.briefApproved && !state.frame?.stale ? "Brief approved" : "Approve brief"}</button>}{view === "storyboard" && <button className="primary-button" disabled={busy || Boolean(state?.storyboardApproved) || Boolean(state?.storyboard.stale)} onClick={() => { void post({ action: "approveStoryboard" }); }}>{state?.storyboardApproved ? "Storyboard approved" : "Approve storyboard"}</button>}{view !== "map" && view !== "storyboard" && <button className="primary-button" disabled={busy} onClick={() => setSheet("library")}>Create</button>}</div>
    </header>

    {notice && <div className="notice" role="status"><span>{notice}</span><button onClick={() => setNotice(null)} aria-label="Dismiss">×</button></div>}

    <section className="object-canvas" aria-label={currentTitle[view]}>
      {view === "map" && <MapCanvas state={state} selectedNode={selectedNode} mapEditing={mapEditing} onMapEditing={() => setMapEditing((value) => !value)} onSelect={setSelectedNodeId} onSync={syncMapCanvas} onDetails={() => setSheet("details")} />}
      {view === "brief" && <BriefView frame={state?.frame} approved={Boolean(state?.briefApproved)} onBack={() => open("map")} />}
      {view === "design" && <DesignView state={state} busy={busy} onPost={post} />}
      {view === "sketch" && <SketchView sketch={state?.sketch} approved={Boolean(state?.briefApproved)} busy={busy} onPost={post} />}
      {view === "storyboard" && <StoryboardView storyboard={state?.storyboard} approved={Boolean(state?.storyboardApproved)} panel={selectedPanel} panelId={selectedPanelId} busy={busy} videoState={state?.videoState} onSelect={setSelectedPanelId} onPost={post} onRender={renderVideo} />}
      {view === "trace" && <TraceView state={state} />}
    </section>

    {sheet === "sources" && <SourcesSheet sources={state?.sourceItems ?? []} selected={selectedSource} onClose={() => setSheet(null)} onSelect={setSelectedSource} onAdd={() => setSheet("add-source")} onCapture={() => setSheet("capture")} onShowMap={(source) => { setSelectedNodeId(state?.mapNodes.find((node) => node.sourceId === source.id)?.id ?? ""); open("map"); }} />}
    {sheet === "library" && <LibrarySheet state={state} canCreate={canCreate} busy={busy} onClose={() => setSheet(null)} onOpen={open} onCreateOutput={createOutput} onCreateImages={() => { void post({ action: "createImageBatch" }); }} onStoryboard={createStoryboard} onRender={renderVideo} />}
    {sheet === "details" && <DetailsSheet state={state} node={selectedNode} mapEditing={mapEditing} onClose={() => setSheet(null)} onOpen={open} onAddIdea={() => { void post({ action: "mapOperation", operation: { type: "add_node", node: { id: `node-manual-${Date.now()}`, kind: "idea", label: "Untitled idea", evidenceState: "creative", metadata: { body: "A user-authored Map idea.", locator: "Manual Map edit" } } } }); }} onExtract={() => { void post({ action: "extractCandidates" }); }} />}
    {sheet === "add-source" && <AddSourceSheet onClose={() => setSheet("sources")} onPost={post} />}
    {sheet === "capture" && <CaptureSheet onClose={() => setSheet("sources")} onPost={post} />}
  </main>;
}

function MapCanvas({ state, selectedNode, mapEditing, onMapEditing, onSelect, onSync, onDetails }: { state: PersistedWorkshop | null; selectedNode?: MapNode; mapEditing: boolean; onMapEditing: () => void; onSelect: (id: string) => void; onSync: (nodes: Pick<MapNode, "id" | "title" | "x" | "y">[]) => void; onDetails: () => void }) {
  const nodes = state?.mapNodes ?? [];
  const displayY = (node: MapNode, index: number) => node.y + nodes.slice(0, index).filter((previous) => Math.abs(previous.x - node.x) < 12 && Math.abs(previous.y - node.y) < 28).length * 12;
  return <div className={`map-canvas ${mapEditing ? "map-editing" : ""}`}><div className="map-caption"><span>{nodes.length ? "Evidence becoming structure" : "Add a source to begin your Map"}</span><button onClick={onMapEditing}>{mapEditing ? "Done editing" : "Edit Map"}</button></div>{mapEditing && <ExcalidrawMap nodes={nodes} editable onSync={onSync} />}{!mapEditing && <><svg className="relationship-lines" aria-hidden="true">{(state?.mapEdges ?? []).map((edge) => { const from = nodes.find((node) => node.id === edge.from.replace(/^node-/, "")); const to = nodes.find((node) => node.id === edge.to.replace(/^node-/, "")); return from && to ? <line key={edge.id} x1={`${from.x}%`} y1={`${from.y}%`} x2={`${to.x}%`} y2={`${to.y}%`} /> : null; })}</svg>{nodes.map((node, index) => <button key={node.id} className={`map-note ${node.kind} ${selectedNode?.id === node.id ? "selected-note" : ""}`} style={{ left: `${node.x}%`, top: `${displayY(node, index)}%` }} onClick={() => onSelect(node.id)}><span>{node.kind}</span><strong>{node.title}</strong><p>{node.body}</p><small>{node.locator}</small></button>)}</>}{selectedNode && !mapEditing && <aside className="map-context"><span className={`evidence-dot ${selectedNode.kind}`} /><div><strong>{selectedNode.title}</strong><p>{selectedNode.locator}</p></div><button onClick={onDetails}>Why this?</button></aside>}</div>;
}

function BriefView({ frame, approved, onBack }: { frame?: PersistedWorkshop["frame"]; approved: boolean; onBack: () => void }) { return <article className="document-view"><div className="document-main"><button className="inline-back" onClick={onBack}>‹ Map</button><h1>FRAME.md</h1><p className="document-intro">{approved && frame && !frame.stale ? "The approved Map is now a brief the rest of WorkshopLM can safely use." : "Approve the current Map to materialize this source-grounded brief."}</p><pre>{frame?.markdown ?? "No approved brief yet."}</pre></div><aside><span className={approved && !frame?.stale ? "state current" : "state waiting"}>{approved && !frame?.stale ? `Current · Map v${frame?.version ?? 1}` : frame?.stale ? "Map changed · refresh needed" : "Waiting for Map approval"}</span><p>Changing the Map after approval marks dependent outputs stale.</p></aside></article>; }

function DesignView({ state, busy, onPost }: { state: PersistedWorkshop | null; busy: boolean; onPost: (body: Record<string, unknown>) => Promise<PersistedWorkshop | null> }) {
  const [name, setName] = useState(state?.style?.name ?? "WorkshopLM editorial"); const [accent, setAccent] = useState(state?.style?.accent ?? "#1668E3"); const [ink, setInk] = useState(state?.style?.ink ?? "#0D0D0D"); const [paper, setPaper] = useState(state?.style?.paper ?? "#FFFFFF");
  const lock = () => { const style: ManualStylePayload = { name, accent, ink, paper, logos: [], licensedFonts: ["system-ui"], references: ["calm editorial work surface"], negativeRules: ["no decorative gradients"], intentProfile: "client_facing_pitch" }; void onPost({ action: "lockManualStyle", manualStyle: style }); };
  return <article className="document-view"><div className="document-main"><h1>DESIGN.md</h1><p className="document-intro">A small, inspectable foundation. Lock it once, then every new output inherits the same visual intent.</p><div className="color-fields"><label>Foundation name<input value={name} onChange={(event) => setName(event.target.value)} /></label><label>Accent<input value={accent} onChange={(event) => setAccent(event.target.value)} /></label><label>Ink<input value={ink} onChange={(event) => setInk(event.target.value)} /></label><label>Paper<input value={paper} onChange={(event) => setPaper(event.target.value)} /></label></div><button className="primary-button" disabled={busy} onClick={lock}>{state?.style && !state.style.stale ? "Update style foundation" : "Lock style foundation"}</button></div><aside><span className={state?.style && !state.style.stale ? "state current" : "state waiting"}>{state?.style && !state.style.stale ? `Current · Style v${state.style.version}` : "Style not locked"}</span><div className="swatch-row"><i style={{ background: accent }} /><i style={{ background: ink }} /><i style={{ background: paper }} /></div><p>Website capture, visual DNA, and exact input provenance remain available in Details.</p></aside></article>;
}

function SketchView({ sketch, approved, busy, onPost }: { sketch?: PersistedWorkshop["sketch"]; approved: boolean; busy: boolean; onPost: (body: Record<string, unknown>) => Promise<PersistedWorkshop | null> }) { return <article className="reading-view"><h1>Sketch</h1><p>{sketch && !sketch.stale ? `A versioned narrative pass from Map revision ${sketch.graphRevision}.` : approved ? "Turn the approved Map into a concise working narrative." : "Approve the Map before creating a Sketch."}</p>{sketch?.nodes?.map((node, index) => <div className="sketch-row" key={node.id}><span>{index + 1}</span><div><strong>{node.title}</strong><p>{node.body}</p><small>{node.locator}</small></div></div>)}<button className="primary-button" disabled={busy || !approved} onClick={() => { void onPost({ action: "createSketch" }); }}>{sketch && !sketch.stale ? "Refresh Sketch" : "Create Sketch"}</button></article>; }

function StoryboardView({ storyboard, approved, panel, panelId, busy, videoState, onSelect, onPost, onRender }: { storyboard?: PersistedWorkshop["storyboard"]; approved: boolean; panel?: PersistedWorkshop["storyboard"]["panels"][number]; panelId: string; busy: boolean; videoState?: PersistedWorkshop["videoState"]; onSelect: (id: string) => void; onPost: (body: Record<string, unknown>) => Promise<PersistedWorkshop | null>; onRender: () => Promise<void> }) {
  const [title, setTitle] = useState(""); const [narration, setNarration] = useState(""); const [seconds, setSeconds] = useState(0);
  useEffect(() => { if (panel) { setTitle(panel.title); setNarration(panel.narration); setSeconds(panel.durationSeconds); } }, [panel?.id]);
  const save = () => panel && void onPost({ action: "updateStoryboardPanel", panel: { id: panel.id, title, narration, durationSeconds: seconds } });
  return <article className="storyboard-view"><div className="storyboard-heading"><div><h1>Storyboard</h1><p>One selected panel at a time. Changes stay editable until approval.</p></div><span className={approved ? "state current" : "state waiting"}>{approved ? "Approved" : "Draft"}</span></div><div className="filmstrip">{(storyboard?.panels ?? []).map((item, index) => <button key={item.id} className={item.id === panel?.id ? "film-frame selected" : "film-frame"} onClick={() => onSelect(item.id)}><span>{index + 1}</span><strong>{item.title}</strong><small>{item.durationSeconds}s</small></button>)}</div>{panel ? <section className="panel-editor"><div className="panel-visual"><span>{panel.title}</span></div><div className="panel-fields"><label>Panel title<input value={title} onChange={(event) => setTitle(event.target.value)} /></label><label>Narration<textarea value={narration} onChange={(event) => setNarration(event.target.value)} /></label><label>Duration (seconds)<input type="number" min="1" value={seconds} onChange={(event) => setSeconds(Number(event.target.value))} /></label><button className="secondary-button" disabled={busy} onClick={save}>Save panel</button></div></section> : <p className="empty-state">Create a storyboard from the Create sheet once your brief and style are current.</p>}{approved && <footer className="storyboard-footer"><span>Storyboard is locked for rendering.</span><button className="primary-button" disabled={busy || videoState === "queued" || videoState === "rendering"} onClick={() => { void onRender(); }}>{videoState === "rendered" ? "Render again" : videoState === "queued" || videoState === "rendering" ? "Rendering…" : "Render approved storyboard"}</button></footer>}</article>;
}

function TraceView({ state }: { state: PersistedWorkshop | null }) { const source = state?.sourceItems[0]; const claim = state?.claims?.[0]; const node = state?.mapNodes[0]; const output = state?.outputs.find((item) => !item.stale); const entries = [source && `Source · ${source.title}`, claim && `Evidence · ${claim.locator}`, node && `Map claim · ${node.title}`, state?.frame && `Brief · FRAME.md v${state.frame.version}`, output && `Output · ${output.type}`].filter(Boolean); return <article className="trace-view"><h1>Why this?</h1><p>WorkshopLM shows the complete available chain, not a confidence-shaped story.</p>{entries.map((entry, index) => <div className="trace-step" key={String(entry)}><span>{index + 1}</span><strong>{entry}</strong></div>)}</article>; }

function SourcesSheet({ sources, selected, onClose, onSelect, onAdd, onCapture, onShowMap }: { sources: SourceItem[]; selected: SourceItem | null; onClose: () => void; onSelect: (source: SourceItem) => void; onAdd: () => void; onCapture: () => void; onShowMap: (source: SourceItem) => void }) { const active = selected ?? sources[0]; return <Sheet title="Sources" onClose={onClose}><div className="sheet-actions"><button className="secondary-button" onClick={onAdd}>Add source</button><button className="secondary-button" onClick={onCapture}>Capture transcript</button></div><div className="source-list">{sources.map((source) => <button key={source.id} className={active?.id === source.id ? "source-item active" : "source-item"} onClick={() => onSelect(source)}><span>{source.type}</span><div><strong>{source.title}</strong><small>{source.origin} · {source.permission} · {source.claimCount} claims</small></div></button>)}</div>{active ? <article className="source-preview"><strong>{active.title}</strong><p>“{active.excerpt}”</p><small>{active.locator}</small><button className="text-button" onClick={() => onShowMap(active)}>Show on Map</button></article> : <p className="empty-state">No source yet. Add a sanitized note, text PDF, or safe public URL.</p>}</Sheet>; }

function LibrarySheet({ state, canCreate, busy, onClose, onOpen, onCreateOutput, onCreateImages, onStoryboard, onRender }: { state: PersistedWorkshop | null; canCreate: boolean; busy: boolean; onClose: () => void; onOpen: (view: ObjectView) => void; onCreateOutput: (type: "deck" | "infographic") => Promise<void>; onCreateImages: () => void; onStoryboard: () => Promise<void>; onRender: () => Promise<void> }) { const items: { label: string; detail: string; view: ObjectView }[] = [{ label: "Map", detail: `${state?.mapNodes.length ?? 0} claims`, view: "map" }, { label: "Brief", detail: state?.frame?.stale ? "Needs review" : state?.frame ? "Current" : "Not approved", view: "brief" }, { label: "Style", detail: state?.style?.stale ? "Needs review" : state?.style ? "Current" : "Not locked", view: "design" }, { label: "Sketch", detail: state?.sketch?.stale ? "Needs review" : state?.sketch ? "Current" : "Not created", view: "sketch" }, { label: "Storyboard", detail: state?.storyboard?.stale ? "Needs review" : state?.storyboard?.panels.length ? `${state.storyboard.panels.length} panels` : "Not created", view: "storyboard" }, { label: "Evidence", detail: "Source to output", view: "trace" }]; return <Sheet title="Workshop library" onClose={onClose}><p className="sheet-intro">Open one durable object. The Map stays the visual home; everything else is a focused review.</p><div className="library-list">{items.map((item) => <button key={item.view} onClick={() => onOpen(item.view)}><strong>{item.label}</strong><small>{item.detail}</small><span>›</span></button>)}</div><h3>Create from current brief + style</h3><div className="create-grid"><button disabled={!canCreate || busy} onClick={() => { void onCreateOutput("deck"); }}>Presentation</button><button disabled={!canCreate || busy} onClick={() => { void onCreateOutput("infographic"); }}>Infographic</button><button disabled={!canCreate || busy} onClick={onCreateImages}>Image set</button><button disabled={!canCreate || busy} onClick={() => { void onStoryboard(); }}>Storyboard</button><button disabled={!state?.storyboardApproved || busy} onClick={() => { void onRender(); }}>Video</button></div>{state?.imageBatch && <p className="sheet-note">Image set: {state.imageBatch.panels.filter((panel) => panel.state === "failed").length ? "partial failure needs retry" : "planned, provider execution not yet authorized"}.</p>}</Sheet>; }

function DetailsSheet({ state, node, mapEditing, onClose, onOpen, onAddIdea, onExtract }: { state: PersistedWorkshop | null; node?: MapNode; mapEditing: boolean; onClose: () => void; onOpen: (view: ObjectView) => void; onAddIdea: () => void; onExtract: () => void }) { return <Sheet title="Details" onClose={onClose}><dl className="detail-list"><dt>Selected claim</dt><dd>{node ? `${node.title} · ${node.locator}` : "Select a Map note"}</dd><dt>Map</dt><dd>{mapEditing ? "Editing canvas" : `${state?.mapNodes.length ?? 0} notes`}</dd><dt>Output state</dt><dd>{state?.videoState ?? "blocked"}</dd><dt>Privacy</dt><dd>Sanitized local fixture</dd></dl><div className="sheet-actions"><button className="secondary-button" onClick={onAddIdea}>Add idea</button><button className="secondary-button" onClick={onExtract}>Extract candidates</button><button className="secondary-button" onClick={() => onOpen("trace")}>Open evidence trace</button></div>{state?.candidates?.length ? <div className="candidate-preview">{state.candidates.slice(0, 4).map((candidate, index) => <p key={`${candidate.text}-${index}`}><span>{candidate.category}</span>{candidate.text}</p>)}</div> : null}</Sheet>; }

function AddSourceSheet({ onClose, onPost }: { onClose: () => void; onPost: (body: Record<string, unknown>) => Promise<PersistedWorkshop | null> }) { const [title, setTitle] = useState(""); const [text, setText] = useState(""); const [url, setUrl] = useState(""); const addText = async () => { const next = await onPost({ action: "ingestSource", source: { title, origin: "Local sanitized note", text, permission: "sanitized" } }); if (next) onClose(); }; const addUrl = async () => { const next = await onPost({ action: "ingestUrl", url }); if (next) onClose(); }; return <Sheet title="Add a source" onClose={onClose}><p className="sheet-intro">Add only material you are allowed to use. Everything is normalized into local, cited evidence.</p><label className="form-field">Title<input value={title} onChange={(event) => setTitle(event.target.value)} placeholder="Sanitized meeting notes" /></label><label className="form-field">Paste text<textarea value={text} onChange={(event) => setText(event.target.value)} placeholder="Paste a bounded, sanitized source." /></label><button className="primary-button" disabled={!title.trim() || !text.trim()} onClick={() => { void addText(); }}>Add text to Map</button><div className="form-divider">or safe public URL</div><label className="form-field"><input type="url" value={url} onChange={(event) => setUrl(event.target.value)} placeholder="https://example.com" /></label><button className="secondary-button" disabled={!url.trim()} onClick={() => { void addUrl(); }}>Fetch and add URL</button></Sheet>; }

function CaptureSheet({ onClose, onPost }: { onClose: () => void; onPost: (body: Record<string, unknown>) => Promise<PersistedWorkshop | null> }) { const [text, setText] = useState(""); const capture = async () => { const next = await onPost({ action: "captureFallbackTranscript", text }); if (next) onClose(); }; return <Sheet title="Capture transcript" onClose={onClose}><p className="sheet-intro">Use the capture-only fallback when native voice synchronization is unavailable. This stores local evidence; it is not a second chat composer.</p><label className="form-field">Transcript segment<textarea value={text} onChange={(event) => setText(event.target.value)} placeholder="Paste or dictate a bounded segment." /></label><button className="primary-button" disabled={!text.trim()} onClick={() => { void capture(); }}>Capture to Workshop</button></Sheet>; }

function Sheet({ title, onClose, children }: { title: string; onClose: () => void; children: React.ReactNode }) { return <aside className="side-sheet" role="dialog" aria-modal="true" aria-label={title}><header><h2>{title}</h2><button className="close-button" onClick={onClose} aria-label={`Close ${title}`}>×</button></header>{children}</aside>; }
